[tasks.build]
command = "docker"
args = ["build", ".", "-t", "ghcr.io/lostb1t/redditbot:latest"]

[tasks.push]
command = "docker"
args = ["push", "ghcr.io/lostb1t/redditbot:latest"]

[tasks.deploy]
run_task = { name = ["build", "push"], fork = false, parallel = false }